### ISSUE TITLE
Duplicate ids.

### ISSUE THREAD

**Issue by vita10gy** [mrcaseb/nflfastR-roster#2]
There's some duplicate Ids in the new roster.

For example 00-0034465

**Comment by mrcaseb** [comment]
Related issue https://github.com/mrcaseb/nflfastR/issues/103

**Comment by mrcaseb** [comment]
Fixed with 18743a3ec379962c6f016b96113b2dd7d31cb689

**Comment by vita10gy** [comment]
I appreciate all the effort.
